import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned dataset (generated by eda.ipynb)
df = pd.read_csv('movies_clean.csv')

# Split genres back into lists and explode
df['genres'] = df['genres'].str.split('|')
df_exploded = df.explode('genres')

# --- App ---
st.title("🎬 Movie Genre Explorer")

# Genre selection
all_genres = sorted(df_exploded['genres'].unique())
selected_genre = st.selectbox("Select a Genre", all_genres)

# Year range slider
min_year = int(df['year'].min())
max_year = int(df['year'].max())
year_range = st.slider("Select Year Range", min_year, max_year, (min_year, max_year))

# Filter movies by genre and year
genre_movies = df_exploded[
    (df_exploded["genres"] == selected_genre) &
    (df_exploded["year"] >= year_range[0]) &
    (df_exploded["year"] <= year_range[1])
][["title", "year", "genres"]]

# Display movies table
st.subheader(f"Movies in '{selected_genre}'")

# Statistics for the current filtered selection
total_movies = len(genre_movies)
avg_year = genre_movies['year'].mean()
oldest = int(genre_movies['year'].min()) if len(genre_movies) else "-"
newest = int(genre_movies['year'].max()) if len(genre_movies) else "-"
most_active_year = int(genre_movies['year'].mode()[0]) if len(genre_movies) else "-"

c1, c2, c3, c4 = st.columns(4)
c1.metric("Total Movies", len(genre_movies))
c2.metric("Avg Release Year", int(avg_year) if len(genre_movies) else "-")
c3.metric("Oldest", oldest)
c4.metric("Most Active Year", most_active_year)

st.dataframe(genre_movies.reset_index(drop=True))

# Genre distribution
st.subheader("Genre Distribution")
genre_counts = df_exploded['genres'].value_counts()
fig1, ax1 = plt.subplots(figsize=(10, 5))
sns.barplot(x=genre_counts.values, y=genre_counts.index, ax=ax1, palette="viridis")
ax1.set_xlabel("Number of Movies")
ax1.set_ylabel("")
st.pyplot(fig1)

# Movies released per year
st.subheader("Movies per Year")
movies_per_year = df.groupby('year')['title'].count()
fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.fill_between(movies_per_year.index, movies_per_year.values, alpha=0.4, color="steelblue")
ax2.plot(movies_per_year.index, movies_per_year.values, color="steelblue", linewidth=2)
ax2.set_xlabel("Year")
ax2.set_ylabel("Number of Movies")
st.pyplot(fig2)

# Top 5 genres pie chart
st.subheader("Top 5 Genres Share")
top_genres = df_exploded['genres'].value_counts().head(5)
fig3, ax3 = plt.subplots(figsize=(7, 7))
ax3.pie(top_genres.values, labels=top_genres.index, autopct='%1.1f%%', startangle=140)
st.pyplot(fig3)
